# This file defines global constants

class Constants:
    DBCONNECTION = "DBCONNECTION"
    MONGOPORT = "MONGOPORT"
    MONGOHOST = "MONGOHOST"
    DATABASENAME = "DATABASENAME"
    MONGODB = "MONGODB"
    
    CONFIGPARSER = "CONFIGPARSER"
    
